Contact form
Flunavgt/Federico-s_Portfolio pull request #3
Opened 2022-07-05 22:31 UTC by Flunavgt

For this PR complete tasks:
Complete Contact form
Created and linked formspree
Set max input char values on contact form
Use flexbox on Form

2022-07-05 23:01 UTC, sumairq requested changes
### Hi @Flunavgt , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️professional README
✔️Correct Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 23:01 UTC, sumairq commented on main.html
> +        </div>
- [ ] Lets make the social icons as close to the Figma design as possible . Cheers 👍 

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/177430439-7d51a4f0-b6f4-4023-928c-f6d07f03ba46.png)  |  ![image](https://user-images.githubusercontent.com/60618877/177430381-7c0a8529-bab6-45b3-8588-3c70e8ece436.png)

2022-07-05 23:46 UTC, tufoinnkuo10 requested changes
Hi @Flunavgt 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ followed figma design 
✅ form submits successfully

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-05 23:46 UTC, tufoinnkuo10 commented on main.html
> +        </div>
- [ ] like the previous reviewer noted, kindly add your social icons so they look like the figma version. they will serve as links to your online sites so they are useful. 
your version 
![Screenshot (210)_LI](https://user-images.githubusercontent.com/65298048/177434495-b2d55d0b-79a7-4cbc-801a-b36cbfa412f4.jpg)
figma version 
![Screenshot (209)_LI](https://user-images.githubusercontent.com/65298048/177434563-ccadde88-d246-4a14-8248-cee3df5a9940.jpg)

2022-07-06 00:09 UTC, sumairq approved these changes
### Hi @Flunavgt  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Followed Figma template
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 01:15 UTC, merged